#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Re-run the corrected 0008_auth.sql against the LIVE Supabase project.
#
# 0008 is already applied there in its pre-hardening form. The corrected
# version adds guard_profile_update and its two triggers, which make user ids
# and usernames immutable, block every self-role change, and restrict
# transitions to and from `super` to super users. Until it runs, the original
# broad UPDATE policy on profiles is what production is enforcing.
#
# Rehearsed 2026-08-06 on a disposable local database built to the live shape:
# applied cleanly, kept every row, installed the guard. This is that rehearsal,
# with the safety checks the rehearsal proved were the ones that matter.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# The wizard reads the project from the repo rather than asking, so it cannot
# be pointed at the wrong database by a typo.
if [[ ! -f supabase/migrations/0008_auth.sql ]]; then
  printf '\n  %sRun this from the repo root%s — supabase/migrations/0008_auth.sql is not here.\n\n' "$RED" "$RESET"
  exit 1
fi

SUPABASE_URL=$(grep -oE "https://[a-z0-9]+\.supabase\.co" src/lib/supabase.js | head -n1)
PROJECT_REF=$(printf '%s' "$SUPABASE_URL" | sed -E 's|https://([a-z0-9]+)\.supabase\.co|\1|')
SQL_EDITOR="https://supabase.com/dashboard/project/${PROJECT_REF}/sql/new"

banner "Re-run the corrected 0008 — project ${PROJECT_REF}"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Confirm the database is in the state this expects"
say "Three things have to be true before anything is applied, and one query"
say "answers all three. The SQL editor shows only the LAST statement's result,"
say "so this is deliberately a single statement."
printf '\n'
open_url "$SQL_EDITOR"
step "Paste this, press Run, and read the three columns:"
cat <<'SQL'

    SELECT
      CASE WHEN EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
                        WHERE n.nspname = 'public' AND p.proname = 'guard_profile_update')
           THEN 'STOP - already done, the corrected 0008 is present'
           ELSE 'ready - the original 0008 is live' END           AS state_0008,
      CASE WHEN to_regclass('public.profiles') IS NULL
           THEN 'STOP - 0008 was never applied at all'
           ELSE 'ok - accounts exist' END                          AS accounts,
      CASE WHEN EXISTS (SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public' AND table_name = 'assignments'
                          AND column_name = 'profile_id')
           THEN 'STOP - 0010 is applied; this wizard assumes it is not'
           ELSE 'ok - 0010 not applied, as expected' END           AS identity_stage;

SQL
printf '\n'
if ! confirm "Do all three columns read 'ready' or 'ok'?"; then
  warn "Stopping. Nothing has been changed."
  note "A 'STOP - already done' means someone has run this; you are finished."
  note "Anything else means the live state is not what ROADMAP.md records — reconcile"
  note "that before applying SQL. supabase/README.md has the audited state table."
  exit 0
fi

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Understand exactly what is about to change"
say "This applies ONE file: supabase/migrations/0008_auth.sql."
printf '\n'
step "It ADDS guard_profile_update() and two triggers on profiles."
step "It REBUILDS the policies on profiles and invites — dropping the existing"
say "  set first, which is why the original's broad UPDATE policy is replaced"
say "  rather than left sitting beside the new ones. Permissive policies OR"
say "  together, so a leftover would keep granting while looking overwritten."
step "It touches NO scouting data. The rehearsal kept every row."
printf '\n'
warn "It does NOT apply 0010, 0011 or 0012."
note "0011 is the one-way door and the cutover is not ready: the client still"
note "ships AUTH_ENFORCED = false, and applying 0011 alone leaves an app that"
note "offers the passphrase, accepts it, and silently rejects every write."
printf '\n'
if ! confirm "Apply the corrected 0008, and nothing else?"; then
  warn "Stopping. Nothing has been changed."
  exit 0
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Apply it"
open_url "$SQL_EDITOR"
step "Open supabase/migrations/0008_auth.sql in your editor."
step "Select the WHOLE file and copy it — it is one transaction, and a partial"
say "  paste commits nothing but wastes the run."
step "Paste into the SQL editor and press Run."
printf '\n'
note "Expect 'Success. No rows returned.' NOTICE lines about triggers that do"
note "not exist are the IF EXISTS guards doing their job on a re-run."
printf '\n'
pause "Press Enter once it has run."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Verify the migration landed"
open_url "$SQL_EDITOR"
step "Paste the whole of supabase/verify_migrations.sql and Run."
printf '\n'
say "Read the top of the result. Failures sort first, so row one tells you"
say "everything. You are looking for:"
printf '\n'
step "NO rows with status FAIL."
step "'0008 complete' — 12 objects present."
step "'auth cutover state is internally consistent' — pre-cutover."
step "'0010 not applied' as INFO, not FAIL. That is expected and correct."
printf '\n'
if ! confirm "Zero FAILs?"; then
  warn "Do not proceed and do not re-run 0008 blindly."
  note "Copy the failing rows and work out which object is missing. A PARTIAL"
  note "migration is the one genuinely dangerous state — it means a transaction"
  note "did not finish."
  exit 1
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify the entries table, and the two toggles no SQL can set"
open_url "$SQL_EDITOR"
step "Paste the whole of supabase/verify_entries.sql and Run."
printf '\n'
say "Expect zero FAILs, and a 'stage' row reading:"
step "'accounts applied, cutover not — 0001 policy set expected'"
note "That file knows which stage the database is at. If it reports post-cutover"
note "here, 0011 has been applied and the live state is not what anyone thinks."
printf '\n'
pause "Press Enter when you have read it."

printf '\n'
say "Now the two dashboard settings no migration can reach. Checking directly:"
printf '\n'
ANON_KEY=$(grep -A3 'SUPABASE_ANON_KEY' src/lib/supabase.js | grep -oE "eyJ[A-Za-z0-9._-]+" | head -n1)
AUTOCONFIRM=$(curl -fsS "${SUPABASE_URL}/auth/v1/settings" -H "apikey: ${ANON_KEY}" 2>/dev/null \
  | grep -oE '"mailer_autoconfirm":[[:space:]]*(true|false)' | grep -oE '(true|false)' || echo "unknown")

if [[ "$AUTOCONFIRM" == "true" ]]; then
  printf '  %s✓%s mailer_autoconfirm: true — Confirm email is OFF, which is correct.\n' "$GREEN" "$RESET"
else
  warn "mailer_autoconfirm: ${AUTOCONFIRM}"
  note "If this is false, Confirm email is ON and registration is not slow — it is"
  note "impossible. Every address is <username>@scout.invalid, RFC 2606 makes"
  note ".invalid permanently unroutable, and GoTrue validates the recipient before"
  note "sending. The error names the address, and the address is fine."
  note "Fix: Authentication → Email → Confirm email OFF, Secure email change OFF."
  SKIPPED+=("Turn Confirm email and Secure email change OFF in the dashboard")
fi

finish
note "0008's hardening is now live: user ids and usernames are immutable, no one"
note "can change their own role, and only supers can promote to or demote from super."
printf '\n'
note "Next in ROADMAP.md is NOT another migration. 0011 needs the client converted"
note "off managerToken first, and it ships in the same deploy as AUTH_ENFORCED = true."
printf '\n'
