#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
#
# Bring the LIVE Supabase project up to the schema the current client expects.
# Two migrations, in order, and deliberately not a third.
#
#   0008 (corrective)  Live has the pre-hardening version. The corrected one
#                      adds guard_profile_update and its two triggers: user ids
#                      and usernames become immutable, self-role changes are
#                      blocked, and only supers may promote to or demote from
#                      super. Until it runs, the original broad UPDATE policy on
#                      profiles is what production enforces.
#
#   0010 (additive)    Adds profile_id beside scout_name on the planning tables.
#                      This one is REQUIRED before the next deploy, not merely
#                      desirable: the client now selects and inserts that column
#                      on assignments, assignment_overrides and reminders.
#                      Deploying without it makes every assignment read fail
#                      with 42703 — for scouts, not just managers.
#
# NOT 0011 or 0012. 0011 is the one-way door, it drops has_manager_token(), and
# the client still ships AUTH_ENFORCED = false. Applying it here would leave an
# app that offers the passphrase, accepts it, and silently rejects every write.
#
# Rehearsed 2026-08-06 — against a database rebuilt from the migrations, NOT
# from production's real shape. `db reset --version 0007` applies 0001, which
# production has never run. See supabase/live_baseline.sql. Treat the expected
# results below as strong expectations, not transcripts of your database.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# ─── clipboard, so nothing has to be copied out of this terminal ───────────
#
# Earlier versions printed SQL here for the human to copy. That is actively
# unsafe: pause() is sitting on `read`, so pasting multi-line text into this
# window feeds line one to read and hands every remaining line to the shell,
# which tries to run SELECT as a command. Put it on the clipboard instead —
# then the only paste target is the browser, where it belongs.
CLIP=""
if   command -v pbcopy   >/dev/null 2>&1; then CLIP="pbcopy"
elif command -v wl-copy  >/dev/null 2>&1; then CLIP="wl-copy"
elif command -v xclip    >/dev/null 2>&1; then CLIP="xclip -selection clipboard"
elif command -v clip.exe >/dev/null 2>&1; then CLIP="clip.exe"
fi

# clip_file PATH "label" — copy a file to the clipboard, or say where it is.
clip_file() {
  local path="$1" label="$2"
  if [[ ! -f "$path" ]]; then
    warn "missing: $path"; return 1
  fi
  if [[ -n "$CLIP" ]]; then
    $CLIP < "$path"
    printf '  %s\xe2\x9c\x93 copied%s %s to the clipboard (%s lines)\n' \
      "$GREEN" "$RESET" "$label" "$(wc -l < "$path" | tr -d ' ')"
    step "Paste into the SQL editor and press Run."
  else
    warn "no clipboard tool found."
    step "Open $path, select all, copy, paste into the SQL editor, Run."
  fi
}

# clip_text "sql" "label" — same, for a query written inline here.
clip_text() {
  if [[ -n "$CLIP" ]]; then
    printf '%s' "$1" | $CLIP
    printf '  %s\xe2\x9c\x93 copied%s %s to the clipboard\n' "$GREEN" "$RESET" "$2"
    step "Paste into the SQL editor and press Run."
  else
    warn "no clipboard tool found — the query is in $2 of supabase/README.md."
  fi
}


if [[ ! -f supabase/migrations/0008_auth.sql ]]; then
  printf '\n  %sRun this from the repo root%s — supabase/migrations/ is not here.\n\n' "$RED" "$RESET"
  exit 1
fi

# Read the project from the repo rather than asking, so a typo cannot point
# this at the wrong database.
SUPABASE_URL=$(grep -oE "https://[a-z0-9]+\.supabase\.co" src/lib/supabase.js | head -n1)
ANON_KEY=$(grep -A3 'SUPABASE_ANON_KEY' src/lib/supabase.js | grep -oE "eyJ[A-Za-z0-9._-]+" | head -n1)
PROJECT_REF=$(printf '%s' "$SUPABASE_URL" | sed -E 's|https://([a-z0-9]+)\.supabase\.co|\1|')
SQL_EDITOR="https://supabase.com/dashboard/project/${PROJECT_REF}/sql/new"

banner "Pending migrations — project ${PROJECT_REF}"

# Convention, stated once: Enter always continues. Every y/N gate asks about the
# exception, so you only type y to stop.

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Check what is actually live"
say "Asked over HTTP, so it costs nothing and cannot be wrong about the target."
printf '\n'
probe_col() {
  local table="$1" col="$2" code
  code=$(curl -s -o /dev/null -w '%{http_code}' \
    "${SUPABASE_URL}/rest/v1/${table}?select=${col}&limit=1" -H "apikey: ${ANON_KEY}" || echo "000")
  printf '%s' "$code"
}
ASSIGN_PROFILE=$(probe_col assignments profile_id)
if [[ "$ASSIGN_PROFILE" == "400" ]]; then
  printf '  %s•%s 0010: NOT applied — assignments.profile_id is absent.\n' "$BLUE" "$RESET"
  NEED_0010=yes
elif [[ "$ASSIGN_PROFILE" == "200" ]]; then
  printf '  %s✓%s 0010: already applied.\n' "$GREEN" "$RESET"
  NEED_0010=no
else
  warn "could not reach the project (HTTP ${ASSIGN_PROFILE}). Check the network and retry."
  exit 1
fi

AUTOCONFIRM=$(curl -fsS "${SUPABASE_URL}/auth/v1/settings" -H "apikey: ${ANON_KEY}" 2>/dev/null \
  | grep -oE '"mailer_autoconfirm":[[:space:]]*(true|false)' | grep -oE '(true|false)' || echo "unknown")
if [[ "$AUTOCONFIRM" == "true" ]]; then
  printf '  %s✓%s Confirm email is OFF (mailer_autoconfirm: true), which is correct.\n' "$GREEN" "$RESET"
else
  warn "mailer_autoconfirm: ${AUTOCONFIRM} — Confirm email appears to be ON."
  note "Registration is then not slow, it is impossible: every address is"
  note "<username>@scout.invalid, RFC 2606 makes .invalid permanently unroutable,"
  note "and GoTrue validates the recipient before sending. Fix it in"
  note "Authentication → Email before anyone tries to register."
  SKIPPED+=("Turn Confirm email OFF, and Secure email change OFF")
fi
# Session length is not readable from /auth/v1/settings, so it cannot be checked
# here — only reminded about. An hour-long token in a gym with no wifi is a scout
# locked out mid-match.
if true; then
  printf '\n'
  note "Not checkable over HTTP, so verify by eye in Authentication -> Sessions:"
  note "  JWT expiry              345600  (4 days)"
  note "  Refresh token rotation  on, reuse interval 60s"
  note "  Session timebox         unset, and inactivity timeout unset"
fi
printf '\n'
pause "Press Enter to check 0008."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Confirm 0008 is still the pre-hardening version"
say "One statement, because the SQL editor shows only the LAST result and a"
say "three-query preflight would silently report just the third."
printf '\n'
open_url "$SQL_EDITOR"
clip_text "SELECT CASE WHEN EXISTS (SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace WHERE n.nspname = 'public' AND p.proname = 'guard_profile_update') THEN 'done - the corrected 0008 is already present' ELSE 'ready - the original 0008 is live' END AS state_0008, CASE WHEN to_regclass('public.profiles') IS NULL THEN 'STOP - 0008 was never applied at all' ELSE 'ok - accounts exist' END AS accounts;" "the 0008 preflight"
printf '\n'
NEED_0008=yes
if confirm "Does state_0008 say 'done' — is 0008 already corrected?"; then
  NEED_0008=no
  note "Skipping stage 3. Nothing to do for 0008."
fi
# Every gate in this wizard asks about the EXCEPTION, so Enter continues.
# This one used to ask "is it correct?", which meant Enter — the [y/N] default,
# and what every pause() in this file trains you to press — answered No, printed
# "Stopping", and exited 0. Silent, success-looking, and it applied nothing.
if [[ "$NEED_0008" == "yes" ]] && confirm "Did EITHER column say STOP?"; then
  warn "Stopping. Nothing has been changed."
  note "Live state is not what ROADMAP.md records. Reconcile before applying SQL."
  exit 1
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Apply the corrected 0008"
if [[ "$NEED_0008" == "no" ]]; then
  note "Already applied — skipped."
  pause "Press Enter to continue."
else
  say "Adds the guard and rebuilds the policies on profiles and invites."
  note "It DROPS the existing policy set before recreating it, which is why the"
  note "original's broad UPDATE policy is replaced rather than left beside the new"
  note "ones. Permissive policies OR together, so a leftover would keep granting"
  note "while looking overwritten."
  printf '\n'
  open_url "$SQL_EDITOR"
  clip_file "supabase/migrations/0008_auth.sql" "the corrected 0008"
  printf '\n'
  note "Expect 'Success. No rows returned.' NOTICE lines about triggers that do"
  note "not exist are the IF EXISTS guards doing their job."
  printf '\n'
  pause "Press Enter once it has run."
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Apply 0010 — the columns the client already expects"
if [[ "$NEED_0010" == "no" ]]; then
  note "Already applied — skipped."
  pause "Press Enter to continue."
else
  warn "This one is required before the next git push."
  say "The deployed client selects and inserts profile_id on assignments,"
  say "assignment_overrides and reminders. Without these columns every"
  say "assignment READ fails with 42703 — for scouts, not just managers."
  printf '\n'
  step "It adds nullable columns, an index each, and profile_for_name()."
  step "It backfills conservatively: one unambiguous match on username or"
  say "  'first last', or NULL. Two people called Alex resolve to nobody."
  step "It changes no policy and touches no scouting observation."
  printf '\n'
  open_url "$SQL_EDITOR"
  clip_file "supabase/migrations/0010_identity.sql" "0010"
  printf '\n'
  pause "Press Enter once it has run."
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Apply 0001 — the corrective migration nobody ever ran"
say "0001 was written to repair this exact table. It is not a create-from-empty"
say "migration: CREATE TABLE IF NOT EXISTS, CREATE INDEX IF NOT EXISTS, CREATE OR"
say "REPLACE FUNCTION, and a DO block that drops every policy by name first."
say "Its own comments say so — \"no-ops once applied\", \"name matches the live"
say "index so re-running does not build a second copy\"."
printf '\n'
step "It drops the created_at and schema_version defaults."
step "It creates entries_session_idx if missing."
step "It re-asserts the policy set 0013 already produced, so that part no-ops."
step "It REVOKEs DELETE from anon and authenticated, which 0013 did not."
printf '\n'
warn "0001 is NOT wrapped in a transaction, and one statement can fail on real"
warn "data: ALTER COLUMN alliance_color SET NOT NULL."
printf '\n'
clip_text "SELECT (SELECT count(*) FROM public.entries WHERE alliance_color IS NULL) AS null_alliance_color, (SELECT count(*) FROM public.entries) AS total_entries, CASE WHEN EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'entries' AND indexname = 'entries_session_idx') THEN 'present' ELSE 'absent - 0001 will create it' END AS entries_session_idx;" "the 0001 preflight"
printf '\n'
if confirm "Is null_alliance_color anything OTHER than 0?"; then
  warn "Stop. Fix those rows first, or 0001 aborts partway through with no"
  warn "transaction to roll it back."
  note "Find them: SELECT id, event_code, match_number, team_number FROM"
  note "public.entries WHERE alliance_color IS NULL;"
  note "Everything before the failure is idempotent, so fixing the rows and"
  note "re-running 0001 completes it."
  exit 1
fi
printf '\n'
clip_file "supabase/migrations/0001_entries.sql" "0001"
printf '\n'
pause "Press Enter once it has run."

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Verify the migrations landed"
open_url "$SQL_EDITOR"
clip_file "supabase/verify_migrations.sql" "verify_migrations.sql"
printf '\n'
say "Failures sort to the top, so row one tells you everything. Expect:"
step "NO rows with status FAIL."
step "'0008 complete' — 14 object(s) present."
step "'0010 complete' — 10 object(s), and '0001 complete' — 4 object(s)."
step "'auth cutover state is internally consistent' — still PRE-cutover."
printf '\n'
note "Pre-cutover is correct and must stay that way: 0011 has not run, and the"
note "client still ships AUTH_ENFORCED = false."
printf '\n'
if confirm "Did ANY row say FAIL?"; then
  warn "Do not re-run blindly."
  note "A PARTIAL migration is the one genuinely dangerous state — it means a"
  note "transaction did not finish. Copy the failing rows and work out which"
  note "object is missing before doing anything else."
  exit 1
fi

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Read the backfill report"
say "0010 guessed identities from typed names. It refused to guess where the"
say "answer was ambiguous, so what stayed NULL is the interesting part — those"
say "are names no account claims."
printf '\n'
open_url "$SQL_EDITOR"
clip_text "SELECT scout_name, count(*) FILTER (WHERE submitted_by IS NULL) AS unmatched, count(*) AS total FROM public.entries GROUP BY scout_name ORDER BY unmatched DESC;" "the backfill report"
printf '\n'
note "unmatched > 0 means either a scout who has not registered yet, or a"
note "spelling nobody uses any more. Neither is an error right now — the client"
note "falls back to matching on the name. Re-run 0010's four UPDATE statements"
note "once everyone has an account, and the number should fall."
printf '\n'
pause "Press Enter when you have looked."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Confirm the entries table, then deploy"
open_url "$SQL_EDITOR"
clip_file "supabase/verify_entries.sql" "verify_entries.sql"
printf '\n'
say "Expect zero FAILs and a 'stage' row reading:"
step "'accounts applied, cutover not — 0001 policy set expected'"
step "'policy set matches' listing entries_session_insert, _select, _update."
printf '\n'
note "This is the check that would have caught the missing UPDATE policy, and it"
note "had never been run here. If it still reports a missing or unexpected policy"
note "after stage 5, 0013 did not take — stop and say so before deploying."
note "Post-cutover as the stage would mean 0011 has run and the live state is not"
note "what anyone thinks."
printf '\n'
pause "Press Enter when you have read it."

finish
note "The database now matches what the committed client expects, so it is safe"
note "to git push. 0008's hardening is live: ids and usernames are immutable, no"
note "one can change their own role, only supers touch super."
printf '\n'
note "Still NOT done, and still not due: 0011 + AUTH_ENFORCED = true ship in one"
note "deploy, after the client stops sending managerToken. See ROADMAP.md step 5."
printf '\n'
